# Generated by Django 5.0.4 on 2024-04-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
