# Generated by Django 5.0.4 on 2024-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
