# Generated by Django 5.0.4 on 2024-04-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecteur', '0002_product_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='totalprice',
            new_name='totalPrice',
        ),
    ]
