# Generated by Django 5.0.4 on 2024-04-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecteur', '0003_rename_totalprice_product_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
